In [21]:
import pandas as pd

In [22]:
df1 = pd.read_csv('DepartmentData.csv')
df2 = pd.read_csv('EmployeeData.csv')

In [23]:
df1.head()

   department_id                 department_name  tax_rate
0              1              Talent Acquisition      0.22
1              2                              HR      0.15
2              3                Customer Service      0.34
3              4  Research and Development (R&D)      0.33
4              5                Public Relations      0.27

In [24]:
df2.head()

               name  age     bonus  base_salary  department_id
0       Steve Smith   46  26048.96        59545              7
1         Eva Brown   31  46217.53        95261             17
2  Charlie Anderson   34  33768.80        97466              8
3   Rachel Martinez   49  30688.55        93735              7
4        Nina White   24  26566.34        56517              1

In [25]:
df3 = pd.merge(df1, df2, on='department_id')
df3

,department_id,department_name,tax_rate,name,age,bonus,base_salary
0,1,Talent Acquisition,0.22,Nina White,24,26566.34,56517
1,1,Talent Acquisition,0.22,Ian Thomas,59,33414.17,91935
2,1,Talent Acquisition,0.22,Tina Lee,40,15327.57,34783
3,1,Talent Acquisition,0.22,Charlie Smith,22,18963.55,52316
4,1,Talent Acquisition,0.22,Pamela Thompson,33,23584.20,59506
...,...,...,...,...,...,...,...
375,19,Logistics,0.13,Alice Smith,52,13909.68,30070
376,19,Logistics,0.13,Tina Davis,29,22863.49,66666
377,19,Logistics,0.13,Pamela Thomas,56,26822.27,86576
378,19,Logistics,0.13,Eva Thomas,49,25658.11,52154
379,19,Logistics,0.13,Pamela Clark,34,22982.06,48687

In [26]:
df3["total_salary"] = df3["base_salary"] + df3["bonus"]
df3

,department_id,department_name,tax_rate,name,age,bonus,base_salary,total_salary
0,1,Talent Acquisition,0.22,Nina White,24,26566.34,56517,83083.34
1,1,Talent Acquisition,0.22,Ian Thomas,59,33414.17,91935,125349.17
2,1,Talent Acquisition,0.22,Tina Lee,40,15327.57,34783,50110.57
3,1,Talent Acquisition,0.22,Charlie Smith,22,18963.55,52316,71279.55
4,1,Talent Acquisition,0.22,Pamela Thompson,33,23584.20,59506,83090.20
...,...,...,...,...,...,...,...,...
375,19,Logistics,0.13,Alice Smith,52,13909.68,30070,43979.68
376,19,Logistics,0.13,Tina Davis,29,22863.49,66666,89529.49
377,19,Logistics,0.13,Pamela Thomas,56,26822.27,86576,113398.27
378,19,Logistics,0.13,Eva Thomas,49,25658.11,52154,77812.11
379,19,Logistics,0.13,Pamela Clark,34,22982.06,48687,71669.06

In [28]:
df3['total_salary'] = df3['total_salary']-(df3['total_salary']*df3['tax_rate'])
average_spectral_salary = df3.groupby("department_name")['total_salary'].mean()
print(average_spectral_salary.sort_values(ascending = False))

department_name
Accounts                          87621.851240
Legal                             84939.271700
Logistics                         83338.993455
Technical                         82845.040600
HR                                82318.159900
Engineering                       77359.799700
Business Development              76212.396535
Education                         70849.017375
Sales                             70457.413325
Talent Acquisition                64335.881610
IT                                63863.460675
Operations                        62301.310400
Finance                           62263.259415
Quality Assurance                 61846.002890
Customer Service                  59702.041410
Research and Development (R&D)    59549.536015
Public Relations                  58952.117980
Marketing                         55113.780900
Product Management                53356.979000
Name: total_salary, dtype: float64